### ISSUE TITLE
Make it so we can change the "Help" and "Phraseology" from light to dark

### ISSUE THREAD

**Issue by unoski1667** [Zedruc/ATC24-Suite-Feedback#11]
**Is your feature request related to a problem? Please describe.**
Yes. It hurts my eyes

**Describe the solution you'd like**
Being able to change from Light to Dark mode

**Additional context**
None :)

**Comment by FormicAcidGD** [comment]
filter: invert(100%);

**Comment by Zedruc** [comment]
I'll go ahead and make the pages adapt to the system theme

**Comment by Zedruc** [comment]
Used the wrong comment button lol

**Comment by Zedruc** [comment]
Alrighty added automatic darkmode with update b-3.2.3
