### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by DangerChamp** [Zedruc/ATC24-Suite-Feedback#2]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Will this be made open source or is this more of a personal project?

**Additional context**
I think it would be interesting to see how the ATC24 community could come together and work on this.

**Comment by Zedruc** [comment]
Hey there, as of now I'm keeping ATC24 closed source for following reasons:
1. The development at this early stage is still very complex with lots of self-written utility classes and libraries, with the principle of "I will self-test as much as I can, and push hotfixes to errors users encounter afterwards".

2. I honestly admit that I do not like the idea of the "Roblox Community" having my code freely available to copy and use themselves at all. While you can of course simply download the website via sketchy tools, going open source would just be giving some people the carte blanche to do whatever.

While the idea of having the community involved in development of this software is indeed a very appealing thought, these are my main 2 reasons.

Maybe I will consider going open source when I personally drop support for this app, but thats a very far future.
