### ISSUE TITLE
[BUG]: Flight strips deleted upon pasting a flightplan

### ISSUE THREAD

**Issue by Koulmoir** [Zedruc/ATC24-Suite-Feedback#3]
Unable to past in flightplans without username they get deleted after a few milli seconds and with username everything is undefined

**Comment by Zedruc** [comment]
Hey koulmoir, thank you for reporting this and apologies for the late reply.
I've investigated this issue and found out it was related to a recent update I pushed regarding user authentication which affected the underlying data transmission between users in a room.

**The issue should be fixed now**, as I just pushed update version `b-2.3.6`.
Thank you once again!

**Comment by Koulmoir** [comment]
No problem,
Thank you for even making such an awesome tool!
