### ISSUE TITLE
Ability to set arrival column

### ISSUE THREAD

**Issue by D1Trimo** [Zedruc/ATC24-Suite-Feedback#31]
**Is your feature request related to a problem? Please describe.**
Whenever you delete the arrival column and create another one, the arrival flightplans don't go into the new one that is made. 

**Describe the solution you'd like**
With another keybind, you can set a column as arrivals

**Additional context**
N/A

**Comment by Zedruc** [comment]
Setting an "arrival column" as a very specific column isn't how this feature is supposed to be used.
The `L` (Create List) and `B` (Delete List) shortcuts should be used if required when opening your room, as your configuration is saved and only overwritten when joining someone else's room.

I could however change the behaviour of the strips to simply go to an adjacent list when the list they are in is deleted.
