### ISSUE TITLE
PDC Generator

### ISSUE THREAD

**Issue by TheAdamsRadial** [Zedruc/ATC24-Suite-Feedback#32]
**Is your feature request related to a problem? Please describe.**
PDCs can take a long time to type out, which can prove disruptive when controlling many planes in an airspace.

**Describe the solution you'd like**
A small button on the flightstrip that automatically copies PDC for that aircraft to be sent to the pilot.

**Additional context**
None.

**Comment by Zedruc** [comment]
Are we talking about CPDLC clearances like this for example:
![cpdlc.jpg](https://github.com/Zedruc/ATC24-Suite-Feedback/assets/69540929/75785d7d-1125-4723-ab3f-e9031e6885f2)

**Comment by TheAdamsRadial** [comment]
My bad. Yes I did mean CPDLC clearances like that.

**Comment by Zedruc** [comment]
Added with version `b-3.3.0`, thanks for the suggestion!
