### ISSUE TITLE
On frequency

### ISSUE THREAD

**Issue by Willek10** [Zedruc/ATC24-Suite-Feedback#38]
**Is your feature request related to a problem? Please describe.**
There's an "On Frequency" status in the majority of controlling softwares. 

**Describe the solution you'd like**
Add a "On Frequency" option for the departures and arrivals abbreviated "FRQ".

**Additional context**
--

**Comment by Zedruc** [comment]
Would this be implemented into the Status cycle or be a checkbox on it's own?
This being in the cycle would be kinda redundant, since you will switch to another status anyways and a checkbox would greatly disturb the design of simple-to-work-with strips
