### ISSUE TITLE
[BUG]: Strip Loading Order Incorect

### ISSUE THREAD

**Issue by realendie** [Zedruc/ATC24-Suite-Feedback#44]
**Describe the bug**
Strips get imported to the bottom of the list.

**To Reproduce**
Wait for a strip to be automatically made by the automatic strip importer.

**Expected behavior**
Strips should be sent to the top of the lists because one it is more realistic as that is how it is used IRL, 2 it is helpful for controllers to manage which aircraft is going to arrive or depart first.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 
 **Additional Info**
 I made this report before the auto import was added and it was implemented, I think it just broke when auto-import was added.

**Comment by Zedruc** [comment]
This is done on on purpose, as flights that get filed later are also expected to arrive/depart later

**Comment by realendie** [comment]
If they were to arrive/depart later they would be on top of the strip list IRL but if you think it should be this way then so be it. You have made a wonderful product after all.
