### ISSUE TITLE
[BUG]: Incorrect flight strip ordering

### ISSUE THREAD

**Issue by realendie** [Zedruc/ATC24-Suite-Feedback#5]
**Describe the bug**
In the ATC24 suite when you make a flight strip it automatically goes to the bottom of the list.
**To Reproduce**
Make a flight strip.

**Expected behavior**
In real life it would go to the top which makes more sense anyway. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera

**Additional context**
Just a minor realism fix.

**Comment by Zedruc** [comment]
Thank you very much for pointing this out!
I just pushed an update to address this

**Comment by realendie** [comment]
Thank you for addressing this
