### ISSUE TITLE
how do i use ifr generator?

### ISSUE THREAD

**Issue by unoski1667** [Zedruc/ATC24-Suite-Feedback#8]

**Comment by Zedruc** [comment]
In the settings in the bottom left enable `Generate IFR clearance shorthand when loading flightplan`, then go into the #flight-plans channel in the Discord, right click a flightplan, click `Copy Text` and paste that into the `PASTE FLIGHTPLAN` field in a flightstrip.
It will generate an IFR clearance looking somewhat like this: `CLR ILAR ALDER1J FPL CVS FL 050 DEP [ ] ?SQ`
![zedruc net_atc24-suite_](https://github.com/Zedruc/ATC24-Suite-Feedback/assets/69540929/92a0f401-ecd5-4288-8aa7-1e902c91a0da)
